FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.frontend.txt .
RUN pip install --no-cache-dir -r requirements.frontend.txt

# Copy the frontend code
COPY ./frontend /app/frontend
COPY ./frontend/server.py /app/server.py

# Create a non-root user
RUN useradd -m frontenduser
USER frontenduser

# Expose the port that Flask runs on
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "server.py"]